name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Java JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Give permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
        shell: bash

      - name: Check if keystore.jks exists
        run: |
          if [ -f keystore.jks ]; then
            echo "Keystore generated successfully!"
          else
            echo "Keystore NOT found!"
            exit 1
          fi

      # 4.5 Generate local.properties
      - name: Generate local.properties
        run: |
         echo "RAWG_API_KEY=${{ secrets.RAWG_API_KEY }}" >> local.properties
         echo "RAWG_CERT_PIN=${{ secrets.RAWG_CERT_PIN }}" >> local.properties
         echo "BASE_URL=${{ secrets.BASE_URL }}" >> local.properties
         echo "HOST_NAME=${{ secrets.HOST_NAME }}" >> local.properties
         echo "PASS_KEY=${{ secrets.PASS_KEY }}" >> local.properties
         echo "KEYSTORE_FILE=keystore.jks" >> local.properties
         echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
         echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> local.properties
         echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Print local.properties
        run: cat local.properties

      # 5. Run Unit Test
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # 6. Build RELEASE APK
      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      # 7. List APK Files Log
      - name: Print APK path
        run: |
          echo "🔍 Searching for APK..."
          find . -type f -name "*.apk"

      # 8. Upload APK sebagai artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ./app/build/outputs/apk/release/app-release.apk
