name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Java JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Give permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore.jks
        shell: bash

      # 5. Build RELEASE APK
      - name: Build Release APK
        run: ./gradlew :app:assembleRelease
        env:
          KEYSTORE_FILE: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
          RAWG_CERT_PIN: ${{ secrets.RAWG_CERT_PIN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          PASS_KEY: ${{ secrets.PASS_KEY }}

      # 6. List APK Files Log
      - name: List APK Files
        run: ls -R app/build/outputs/apk/

      # 7. Run Unit Test
      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest

      # 8. Upload APK sebagai artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
